### ISSUE TITLE
Full of Errors, Projectors won´t work at all.

### ISSUE THREAD

**Issue by MrDinoCarlos** [corentingosselin/ProdigyNightclubWiki#13]
Hello there.
First of all I love your plugin, I´ve just bought it but nothing gets to work.
I´ve tried with several tutorial but nothing, they are outdated with another version.

For example when I try to place some projector, within the nightclub, they will place correctly but won´t toggle. Also when I reload the server the projectors are just there but they wont toggle, they don´t even exist.

Also when I enter edit mode, make some changes and exit I get an error.

Here are some errors I found on the console log. I don´t know if its cause I´m doing something wrong or it´s a plugins fault.

`[13:13:02] [Server thread/ERROR]: Could not pass event QuitNightClubEvent to ProdigyNightclub v3.0.65
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at fr.cocoraid.prodigynightclub.listener.listeners.EnterQuitNightclubListener.move(EnterQuitNightclubListener.java:78) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor199.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1252) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.network.protocol.game.PacketPlayInFlying.a(SourceFile:114) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:16) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1102) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int[])'
        at fr.cocoraid.prodigynightclub.nightclub.projector.Projector.despawn(Projector.java:121) ~[?:?]
        at fr.cocoraid.prodigynightclub.nightclub.Nightclub.lambda$unload$3(Nightclub.java:92) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at fr.cocoraid.prodigynightclub.nightclub.Nightclub.unload(Nightclub.java:90) ~[?:?]
        at fr.cocoraid.prodigynightclub.listener.listeners.EnterQuitNightclubListener.quit(EnterQuitNightclubListener.java:32) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        ... 26 more
[13:13:21] [Server thread/INFO]: BichoBolaYT issued server command: /pnc projector toggle 0
[13:13:27] [Server thread/INFO]: BichoBolaYT issued server command: /pnc projector toggle 0
[13:13:27] [Server thread/ERROR]: [ACF] Exception in command: prodigynightclub projector toggle 0
[13:13:27] [Server thread/ERROR]: [ACF] java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int[])'
[13:13:27] [Server thread/ERROR]: [ACF]         at fr.cocoraid.prodigynightclub.nightclub.projector.laser.lasers.GuardianLaser.remove(GuardianLaser.java:127)
[13:13:27] [Server thread/ERROR]: [ACF]         at fr.cocoraid.prodigynightclub.nightclub.projector.Projector.stopProjector(Projector.java:191)
[13:13:27] [Server thread/ERROR]: [ACF]         at fr.cocoraid.prodigynightclub.nightclub.projector.Projector.turnProjector(Projector.java:185)
[13:13:27] [Server thread/ERROR]: [ACF]         at fr.cocoraid.prodigynightclub.commands.admin.ProjectorCMD.onProjectorToggle(ProjectorCMD.java:133)
[13:13:27] [Server thread/ERROR]: [ACF]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:13:27] [Server thread/ERROR]: [ACF]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[13:13:27] [Server thread/ERROR]: [ACF]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:13:27] [Server thread/ERROR]: [ACF]         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[13:13:27] [Server thread/ERROR]: [ACF]         at fr.cocoraid.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[13:13:27] [Server thread/ERROR]: [ACF]         at fr.cocoraid.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[13:13:27] [Server thread/ERROR]: [ACF]         at fr.cocoraid.acf.BaseCommand.execute(BaseCommand.java:513)
[13:13:27] [Server thread/ERROR]: [ACF]         at fr.cocoraid.acf.RootCommand.execute(RootCommand.java:99)
[13:13:27] [Server thread/ERROR]: [ACF]         at fr.cocoraid.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[13:13:27] [Server thread/ERROR]: [ACF]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[13:13:27] [Server thread/ERROR]: [ACF]         at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1944)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.server.TickTask.run(SourceFile:18)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1102)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031)
[13:13:27] [Server thread/ERROR]: [ACF]         at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[13:13:27] [Server thread/ERROR]: [ACF]         at java.base/java.lang.Thread.run(Thread.java:831)`

`[13:12:37] [Server thread/INFO]: [ProdigyNightclub] Disabling ProdigyNightclub v3.0.65
[13:12:37] [Server thread/ERROR]: Error occurred while disabling ProdigyNightclub v3.0.65 (Is it up to date?)
java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int[])'
        at fr.cocoraid.prodigynightclub.nightclub.projector.Projector.despawn(Projector.java:99) ~[?:?]
        at fr.cocoraid.prodigynightclub.nightclub.Nightclub.lambda$unload$2(Nightclub.java:83) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at fr.cocoraid.prodigynightclub.nightclub.Nightclub.unload(Nightclub.java:81) ~[?:?]
        at fr.cocoraid.prodigynightclub.ProdigyNightclub.lambda$onDisable$4(ProdigyNightclub.java:167) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at fr.cocoraid.prodigynightclub.ProdigyNightclub.onDisable(ProdigyNightclub.java:166) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:493) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.plugin.SimplePluginManager.clearPlugins(SimplePluginManager.java:544) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:848) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.Bukkit.reload(Bukkit.java:651) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1944) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1101) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3136-Spigot-66f9d3c-ea1a843]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by corentingosselin** [comment]
Hello,

Could confirm me your server version ? because you need 1.17.1 not 1.17
Also the only official tutorial for latest version is the [wiki](https://github.com/corentingosselin/ProdigyNightclubWiki/wiki)

**Comment by MrDinoCarlos** [comment]
Indeed it's 1.17.

I'll try with 1.17.1 and see if I get no errors, hope so.
And I'll let you know if it works.

Also do you know if there is any updated youtube tutorial video ?


Thanks for the quick response.



P.S. I've seen there is a golem for like door staff. How can I get it out and working? I haven't seen the option, probably cause I was using 1.17 not 1.17.1.

**Comment by corentingosselin** [comment]
Yes videos are included into the wiki
The iron golem has been temp removed. I am adding new staff members as fast as I can

**Comment by MrDinoCarlos** [comment]
Thanks man!
I'll love to see the next update.

Also if you need help with translating to spanish I could gladly help you with that.


Best Regards.

**Comment by MrDinoCarlos** [comment]
It works with 1.17.1
Is there any way to bind projectors / effects to any lever or system that you can control manually?

**Comment by corentingosselin** [comment]
> Also if you need help with translating to spanish I could gladly help you with that.

Thank you for your offer , for the moment there are not so much to translate ;)

> It works with 1.17.1 Is there any way to bind projectors / effects to any lever or system that you can control manually?

You can use command blocks, don't forget to put the name of the nightclub in the command like:

/pnc projector toggle nightclub 0
