### ISSUE TITLE
Can't save edits

### ISSUE THREAD

**Issue by catpawzz** [corentingosselin/ProdigyNightclubWiki#18]
Hi, i just bought the plugin, I sucessfully made the Arena but when i Try to save my config of Projectors with **/pnc edit save** it says this in console. I'm using the 1.17 version

[16:56:29 ERROR]: [ProdigyNightclub] [ACF] Exception in command: prodigynightclub edit save 
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)'
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub.jar//fr.cocoraid.prodigynightclub.manager.menu.ItemClickable.despawn(ItemClickable.java:70)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub.jar//fr.cocoraid.prodigynightclub.manager.menu.MoveMenu3D.destroy(MoveMenu3D.java:139)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub.jar//fr.cocoraid.prodigynightclub.manager.setup.EditorMode.stopEditor(EditorMode.java:166)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub.jar//fr.cocoraid.prodigynightclub.manager.setup.EditorMode.stopAndSave(EditorMode.java:188)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub.jar//fr.cocoraid.prodigynightclub.commands.setup.EditorCMD.onEditSave(EditorCMD.java:107)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub.jar//fr.cocoraid.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub.jar//fr.cocoraid.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub.jar//fr.cocoraid.acf.BaseCommand.execute(BaseCommand.java:513)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub.jar//fr.cocoraid.acf.RootCommand.execute(RootCommand.java:99)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub.jar//fr.cocoraid.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2330)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2141)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2122)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1441)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1419)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1412)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1390)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1301)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[16:56:29 ERROR]: [ProdigyNightclub] [ACF] 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by yumithecat** [comment]
It does this for multiple commands of the plugin

**Comment by catpawzz** [comment]
Since github is bugging on my pc, could you please contact me on my discord? Yumithecat#0001

**Comment by corentingosselin** [comment]
If you are using 1.17.1 (3.0.65) : https://www.spigotmc.org/resources/prodigynightclub.58234/download?version=412277
If you are using 1.17 (3.0.64): https://www.spigotmc.org/resources/prodigynightclub.58234/download?version=405003

If you are using 1.17.2, the plugin is not compatible.

However I highly recommend you to use the latest version for 1.18.2

**Comment by catpawzz** [comment]
I Use 1.17.1 but I have plugins that are not compatible with 1.18.2 that's the main reason...

**Comment by corentingosselin** [comment]
So, are you sure you download the 3.0.65 version ?

**Comment by catpawzz** [comment]
After downloading the one you gave me it works perfectly. Thanks for your fast support!
