### ISSUE TITLE
Creating a projector is not working

### ISSUE THREAD

**Issue by cynicalmax** [corentingosselin/ProdigyNightclubWiki#19]
creating a projector still doesn´t work.
I´m currently on an 1.18.1 paperMC server.

The plugin throws this out:
[18:40:40 INFO]: cynicalmax issued server command: /pnc projector create
[18:40:40 ERROR]: [ProdigyNightclub] [ACF] Exception in command: prodigynightclub projector create
[18:40:40 ERROR]: [ProdigyNightclub] [ACF] java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R2/CraftWorld
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at ProdigyNightclub.jar//fr.cocoraid.prodigynightclub.nms.ArmorstandNMS.&lt;init>(ArmorstandNMS.java:18)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at ProdigyNightclub.jar//fr.cocoraid.prodigynightclub.manager.menu.ItemClickable.&lt;init>(ItemClickable.java:28)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at ProdigyNightclub.jar//fr.cocoraid.prodigynightclub.manager.menu.MoveMenu3D.&lt;init>(MoveMenu3D.java:35)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at ProdigyNightclub.jar//fr.cocoraid.prodigynightclub.manager.setup.EditorMode.&lt;init>(EditorMode.java:59)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at ProdigyNightclub.jar//fr.cocoraid.prodigynightclub.manager.setup.EditorMode.&lt;init>(EditorMode.java:75)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at ProdigyNightclub.jar//fr.cocoraid.prodigynightclub.manager.setup.EditorMode.addEditor(EditorMode.java:358)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at ProdigyNightclub.jar//fr.cocoraid.prodigynightclub.commands.admin.ProjectorCMD.onProjectorCreate(ProjectorCMD.java:64)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at ProdigyNightclub.jar//fr.cocoraid.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at ProdigyNightclub.jar//fr.cocoraid.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at ProdigyNightclub.jar//fr.cocoraid.acf.BaseCommand.execute(BaseCommand.java:513)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at ProdigyNightclub.jar//fr.cocoraid.acf.RootCommand.execute(RootCommand.java:99)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at ProdigyNightclub.jar//fr.cocoraid.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:908)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2289)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2100)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2081)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1423)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1393)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1371)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1277)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      at java.base/java.lang.Thread.run(Thread.java:833)
[18:40:40 ERROR]: [ProdigyNightclub] [ACF] Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R2.CraftWorld
[18:40:40 ERROR]: [ProdigyNightclub] [ACF]      ... 37 more
[18:40:41 WARN]: [ProdigyNightclub] Plugin ProdigyNightclub v3.0.71 generated an exception while executing task 22141
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R2/entity/CraftPlayer
        at fr.cocoraid.prodigynightclub.nms.NMS.sendPacket(NMS.java:114) ~[ProdigyNightclub.jar:?]
        at fr.cocoraid.prodigynightclub.nms.NMS.lambda$sendPacket$1(NMS.java:34) ~[ProdigyNightclub.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at fr.cocoraid.prodigynightclub.nms.NMS.sendPacket(NMS.java:33) ~[ProdigyNightclub.jar:?]
        at fr.cocoraid.prodigynightclub.commands.admin.NightclubCMD$1.lambda$run$0(NightclubCMD.java:159) ~[ProdigyNightclub.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at fr.cocoraid.prodigynightclub.commands.admin.NightclubCMD$1.run(NightclubCMD.java:157) ~[ProdigyNightclub.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-216]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-216]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-216]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer
        ... 21 more

**Comment by corentingosselin** [comment]
Hello,

Prodigynightclub has been updated for 1.18.2 only

**Comment by cynicalmax** [comment]
Thank you!
