### ISSUE TITLE
example scenario don't work

### ISSUE THREAD

**Issue by PanetiX** [corentingosselin/ProdigyNightclubWiki#25]
Hello, when i rename the example_scenario.json file to "test.json" and try to reload the plugin or restart the server, the plugin don't work anymore.

log says me to do that...
[19:09:35] [Server thread/INFO]: INFO: example_scenario.json is detected !
[19:09:35] [Server thread/INFO]:  - Path: plugins/ProdigyNightclub/nightclubs/nightclub/scenario/example_scenario.json
[19:09:35] [Server thread/INFO]:  - This scenario is not used by ProdigyNightclub, rename the file if you want to load it

error-log:
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] Exception in command: prodigynightclub reload 
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] java.lang.NullPointerException: Cannot invoke "fr.cocoraid.prodigynightclub.nightclub.effect.Effect.deserialize(com.google.gson.JsonObject)" because "<local8>" is null
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub-3.1.1.jar//fr.cocoraid.prodigynightclub.scenario.json.effects.EffectActionDeserializer.deserialize(EffectActionDeserializer.java:39)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub-3.1.1.jar//fr.cocoraid.prodigynightclub.scenario.json.effects.EffectActionDeserializer.deserialize(EffectActionDeserializer.java:14)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:431)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:391)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:431)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:391)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.Gson.fromJson(Gson.java:1214)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.google.gson.Gson.fromJson(Gson.java:1173)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub-3.1.1.jar//fr.cocoraid.prodigynightclub.scenario.ScenarioLoader.load(ScenarioLoader.java:65)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub-3.1.1.jar//fr.cocoraid.prodigynightclub.file.nightclub.NightclubsLoader.load(NightclubsLoader.java:78)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub-3.1.1.jar//fr.cocoraid.prodigynightclub.commands.admin.NightclubCMD.onPluginReload(NightclubCMD.java:112)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub-3.1.1.jar//fr.cocoraid.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub-3.1.1.jar//fr.cocoraid.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub-3.1.1.jar//fr.cocoraid.acf.BaseCommand.execute(BaseCommand.java:513)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub-3.1.1.jar//fr.cocoraid.acf.RootCommand.execute(RootCommand.java:99)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at ProdigyNightclub-3.1.1.jar//fr.cocoraid.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:313)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:297)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[19:12:52] [Server thread/ERROR]: [ProdigyNightclub] [ACF] 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by corentingosselin** [comment]
The example scenario is not attached to any nightclub, it means this will not working if you do not edit this file.
You need to add effect with ids that are existing in nightclub you setup.
I added an warning message instead of the error you get for the next update
