### ISSUE TITLE
Not Starting

### ISSUE THREAD

**Issue by Abyss-Mage** [corentingosselin/ProdigyNightclubWiki#27]
[10:01:42 ERROR]: Error occurred (in the plugin loader) while disabling ProdigyNightclub v3.2.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "fr.cocoraid.prodigynightclub.manager.NightclubManager.getNightclubs()" because the return value of "fr.cocoraid.prodigynightclub.ProdigyNightclub.getNightclubManager()" is null
        at fr.cocoraid.prodigynightclub.ProdigyNightclub.onDisable(ProdigyNightclub.java:198) ~[Atlantist.site_ProdigyNightClub_3.2.1-q.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at fr.cocoraid.prodigynightclub.ProdigyNightclub.onEnable(ProdigyNightclub.java:114) ~[Atlantist.site_ProdigyNightClub_3.2.1-q.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:660) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:571) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:632) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[10:01:42 INFO]:  Could not load prodigynightclub because you must run the latest spigot version 1.19
[10:01:42 ERROR]: Error occurred while enabling ProdigyNightclub v3.2.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:548) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:248) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:244) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:189) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:158) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at fr.cocoraid.prodigynightclub.utils.UpdateChecker.getVersion(UpdateChecker.java:24) ~[Atlantist.site_ProdigyNightClub_3.2.1-q.jar:?]
        at fr.cocoraid.prodigynightclub.ProdigyNightclub.onEnable(ProdigyNightclub.java:120) ~[Atlantist.site_ProdigyNightClub_3.2.1-q.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:660) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:571) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:632) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by corentingosselin** [comment]
Can you add more context to this error ? did you reproduce using spigot not purpur ?
