### ISSUE TITLE
I know it's for spigot, but maybe there's a simple solution for this initialization error in the paper.

### ISSUE THREAD

**Issue by faalzz** [corentingosselin/ProdigyNightclubWiki#30]
java.lang.NumberFormatException: For input string: "#"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122) ~[?:?]
	at java.base/java.lang.Float.parseFloat(Float.java:556) ~[?:?]
	at ProdigyNightclub-4.0.2.jar/fr.cocoraid.prodigynightclub.nightclub.armor.ArmorStandMovement.<init>(ArmorStandMovement.java:33) ~[ProdigyNightclub-4.0.2.jar:?]
	at ProdigyNightclub-4.0.2.jar/fr.cocoraid.prodigynightclub.file.nightclub.NightclubsLoader.loadMovements(NightclubsLoader.java:154) ~[ProdigyNightclub-4.0.2.jar:?]
	at ProdigyNightclub-4.0.2.jar/fr.cocoraid.prodigynightclub.file.nightclub.NightclubsLoader.load(NightclubsLoader.java:48) ~[ProdigyNightclub-4.0.2.jar:?]
	at ProdigyNightclub-4.0.2.jar/fr.cocoraid.prodigynightclub.ProdigyNightclub.onEnable(ProdigyNightclub.java:171) ~[ProdigyNightclub-4.0.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:50:21] [Server thread/INFO]: [ProdigyNightclub] Disabling ProdigyNightclub v4.0.2
[20:50:21] [Server thread/ERROR]: Error occurred while disabling ProdigyNightclub v4.0.2
java.lang.NullPointerException: Cannot invoke "fr.cocoraid.prodigynightclub.file.event.EventLoader.unload()" because "this.eventLoader" is null
	at ProdigyNightclub-4.0.2.jar/fr.cocoraid.prodigynightclub.ProdigyNightclub.onDisable(ProdigyNightclub.java:207) ~[ProdigyNightclub-4.0.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by corentingosselin** [comment]
Not reproductible even using paper spigot, probably an issue with the server host. I will do some test using external host to reproduce
