### ISSUE TITLE
DragonEffect exception 

### ISSUE THREAD

**Issue by NeadApTar** [corentingosselin/ProdigyNightclubWiki#7]
Flood in console every 2 seconds 🤔
```
[00:56:29 WARN]: [ProdigyNightclub] Plugin ProdigyNightclub v3.0.61 generated an exception while executing task 154919
java.lang.IndexOutOfBoundsException: Index 126650698 out of bounds for length 444
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
	at java.util.ArrayList.remove(ArrayList.java:536) ~[?:?]
	at fr.cocoraid.prodigynightclub.nightclub.effect.effects.DragonEffect$1.run(DragonEffect.java:68) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-587]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-587]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-587]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

```yml
dragon:
  '0':
    location:
      ==: org.bukkit.Location
      world: world_the_end
      x: 27.5
      y: 72.0
      z: 0.5
      pitch: 19.600355
      yaw: -19.579132
    renderSpeed: 30
    ```

**Comment by corentingosselin** [comment]
I'm not 100% sure this will be fixed for the next version, but feel free to open another ticket :)
